CREATE DATABASE SH CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE SH;

TRUNCATE TABLE SH.SHEET;

CREATE TABLE IF NOT EXISTS SH.SHEET (
  ID                    BIGINT NOT NULL AUTO_INCREMENT,
  CUSTOMER              VARCHAR(255),
  TEST_TYPE             VARCHAR(255),
  PSV_NO                VARCHAR(255),
  FLUID                 VARCHAR(255),
  SERIAL_NO             VARCHAR(255),
  LOCATION              VARCHAR(255),
  MAKER                 VARCHAR(255),
  VELVE_TYPE            VARCHAR(255),
  INLET_SIZE            BIGINT,
  OUTLET_SIZE           BIGINT,
  TEST_DATE             VARCHAR(255),
  SET_PRESS             FLOAT(10,2),
  BACK_PRESS            FLOAT(10,2),
  COLD_PRESS            FLOAT(10,2),
  RESULT_SET_PRESS      FLOAT(10,2),
  RESULT_COLD_PRESS     FLOAT(10,2),
  RESULT_BACK_PRESS     FLOAT(10,2),
  RESULT_POP_PRESS      FLOAT(10,2),
  RESULT_LEAK_PRESS     FLOAT(10,2),
  RESULT_OK             VARCHAR(255),
  ADJUST_SCREW          FLOAT(10,2),
  UPPERING              BIGINT,
  LOWERING              BIGINT,
  WORKER                VARCHAR(255),
  INSPECTOR             VARCHAR(255),
  MANAGER               VARCHAR(255),
  PRIMARY KEY (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;
